### ISSUE TITLE
using OTR4j with SMACK

### ISSUE THREAD

**Issue by ronnycsharp** [jitsi/otr4j#1]
Hello,
I want to develop an android client for xmpp-communication.
At the Moment I am using the Smack-Library. But I also want the OTR-Encryption.
Do you know if OTR4j works with the Smack-Library?

I hope anyone could help.

Regards
Ronny

**Comment by ronnycsharp** [comment]
Hello,
I want to develop an android client for xmpp-communication.
At the Moment I am using the Smack-Library. But I also want the OTR-Encryption.
Do you know if OTR4j works with the Smack-Library?

Regards
Ronny

**Comment by a-iv** [comment]
@ronnycsharp, https://github.com/redsolution/xabber-android uses modified version of Smack.
Also it uses this version of OTR4J.

**Comment by ronnycsharp** [comment]
Great! Thank you! It looks nice.
