### ISSUE TITLE
Transfer of the unmaintained repository

### ISSUE THREAD

**Issue by Neustradamus** [jitsi/otr4j#2]
@andrewnenakhov: it is possible to transfer this repository to me?

The OTR4J team must to relive completely this project :)
- https://github.com/otr4j/otr4j

Thanks in advance.

**Comment by andrewnenakhov** [comment]
@Neustradamus It is definitely not impossible, but what are you going to do with it?

**Comment by Neustradamus** [comment]
@andrewnenakhov: Why impossible?

**Comment by andrewnenakhov** [comment]
@Neustradamus actually I have said, 'not impossible', which means, 'possible'. 

Anyway, I'm not sure I understand the context of the process well. There was a message on jitsy/otr4j repo by  @cobratbq  which I didn't fully understand. I believe that whoever does the most coding should call the shots (if there is just one party that does, his repository should be the main onw). But who's that person, I don't know.

**Comment by Neustradamus** [comment]
@andrewnenakhov: The goal is to have the main project in this old repository, all will be integrated...
- Look here: https://github.com/otr4j/otr4j/commits?author=cobratbq

A lot of, the beginning is here:
- https://github.com/otr4j/otr4j/commits?after=31eb1144a8313822acedff87f1417cb1db6c736c+1504&author=cobratbq

Thanks in advance.

**Comment by andrewnenakhov** [comment]
Allright. @a-iv will transfer you the ownership whe he gets to the computer.

**Comment by Neustradamus** [comment]
@andrewnenakhov, @a-iv: Thanks in advance :)

**Comment by Neustradamus** [comment]
@andrewnenakhov, @a-iv: Thanks, it is done! :)
